spring:
  main:
    allow-circular-references: 'true'
  application:
    name: spring-backend
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/coursestemp
    password: postgres
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: myrealm
  public-client: 'true'
  resource: spring
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true